(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.SC = root.SC || {};
    root.SC.jugadores = factory();
  }
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  // Generado por tools/generar-jugadores.js a partir de data/jugadores-base.csv.
  // No editar a mano: correr `node subasta-futbol/tools/generar-jugadores.js`.
  var JUGADORES = [
  {
    "id": 1,
    "nombre": "Lev Yashin",
    "nombreCarta": "Yashin",
    "pais": "Rusia",
    "bandera": "🇷🇺",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 1963,
    "club": "Dinamo Moscú",
    "siglaClub": "DIN",
    "ovr": 95,
    "categoria": "Leyenda",
    "carta": {
      "est": 96,
      "par": 93,
      "saq": 80,
      "ref": 97,
      "vel": 68,
      "col": 94
    },
    "ata": 28,
    "cre": 48,
    "def": 47,
    "arq": 95
  },
  {
    "id": 2,
    "nombre": "Gianluigi Buffon",
    "nombreCarta": "Buffon",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 2006,
    "club": "Juventus",
    "siglaClub": "JUV",
    "ovr": 94,
    "categoria": "Crack",
    "carta": {
      "est": 88,
      "par": 99,
      "saq": 79,
      "ref": 99,
      "vel": 84,
      "col": 90
    },
    "ata": 28,
    "cre": 47,
    "def": 45,
    "arq": 94
  },
  {
    "id": 3,
    "nombre": "Manuel Neuer",
    "nombreCarta": "Neuer",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 2014,
    "club": "Bayern Múnich",
    "siglaClub": "BAY",
    "ovr": 93,
    "categoria": "Crack",
    "carta": {
      "est": 91,
      "par": 91,
      "saq": 98,
      "ref": 95,
      "vel": 89,
      "col": 95
    },
    "ata": 34,
    "cre": 59,
    "def": 48,
    "arq": 93
  },
  {
    "id": 4,
    "nombre": "Iker Casillas",
    "nombreCarta": "Casillas",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 2010,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 92,
    "categoria": "Crack",
    "carta": {
      "est": 86,
      "par": 95,
      "saq": 77,
      "ref": 99,
      "vel": 82,
      "col": 88
    },
    "ata": 27,
    "cre": 46,
    "def": 44,
    "arq": 92
  },
  {
    "id": 5,
    "nombre": "Peter Schmeichel",
    "nombreCarta": "Schmeichel",
    "pais": "Dinamarca",
    "bandera": "🇩🇰",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 1999,
    "club": "Manchester United",
    "siglaClub": "MUN",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "est": 99,
      "par": 81,
      "saq": 83,
      "ref": 89,
      "vel": 77,
      "col": 95
    },
    "ata": 29,
    "cre": 50,
    "def": 48,
    "arq": 91
  },
  {
    "id": 6,
    "nombre": "Gordon Banks",
    "nombreCarta": "Banks",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 1970,
    "club": "Stoke City",
    "siglaClub": "STK",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "est": 85,
      "par": 93,
      "saq": 76,
      "ref": 99,
      "vel": 81,
      "col": 87
    },
    "ata": 27,
    "cre": 46,
    "def": 44,
    "arq": 91
  },
  {
    "id": 7,
    "nombre": "Dino Zoff",
    "nombreCarta": "Zoff",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 1982,
    "club": "Juventus",
    "siglaClub": "JUV",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "est": 93,
      "par": 91,
      "saq": 75,
      "ref": 83,
      "vel": 77,
      "col": 97
    },
    "ata": 26,
    "cre": 45,
    "def": 49,
    "arq": 91
  },
  {
    "id": 8,
    "nombre": "Oliver Kahn",
    "nombreCarta": "Kahn",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 2002,
    "club": "Bayern Múnich",
    "siglaClub": "BAY",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "est": 99,
      "par": 79,
      "saq": 82,
      "ref": 88,
      "vel": 76,
      "col": 94
    },
    "ata": 29,
    "cre": 49,
    "def": 47,
    "arq": 90
  },
  {
    "id": 9,
    "nombre": "Sepp Maier",
    "nombreCarta": "Maier",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 1974,
    "club": "Bayern Múnich",
    "siglaClub": "BAY",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "est": 92,
      "par": 90,
      "saq": 74,
      "ref": 82,
      "vel": 76,
      "col": 96
    },
    "ata": 26,
    "cre": 44,
    "def": 48,
    "arq": 90
  },
  {
    "id": 10,
    "nombre": "Thibaut Courtois",
    "nombreCarta": "Courtois",
    "pais": "Bélgica",
    "bandera": "🇧🇪",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 2022,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "est": 89,
      "par": 89,
      "saq": 83,
      "ref": 89,
      "vel": 83,
      "col": 89
    },
    "ata": 29,
    "cre": 50,
    "def": 45,
    "arq": 89
  },
  {
    "id": 11,
    "nombre": "Alisson Becker",
    "nombreCarta": "Alisson",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 2019,
    "club": "Liverpool",
    "siglaClub": "LIV",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "est": 87,
      "par": 87,
      "saq": 94,
      "ref": 91,
      "vel": 85,
      "col": 91
    },
    "ata": 33,
    "cre": 56,
    "def": 46,
    "arq": 89
  },
  {
    "id": 12,
    "nombre": "Ricardo Zamora",
    "nombreCarta": "Zamora",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 1934,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "est": 90,
      "par": 88,
      "saq": 72,
      "ref": 80,
      "vel": 74,
      "col": 94
    },
    "ata": 25,
    "cre": 43,
    "def": 47,
    "arq": 88
  },
  {
    "id": 13,
    "nombre": "Edwin van der Sar",
    "nombreCarta": "Van der Sar",
    "pais": "Países Bajos",
    "bandera": "🇳🇱",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 2008,
    "club": "Manchester United",
    "siglaClub": "MUN",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "est": 86,
      "par": 86,
      "saq": 93,
      "ref": 90,
      "vel": 84,
      "col": 90
    },
    "ata": 33,
    "cre": 56,
    "def": 45,
    "arq": 88
  },
  {
    "id": 14,
    "nombre": "Petr Čech",
    "nombreCarta": "Cech",
    "pais": "Chequia",
    "bandera": "🇨🇿",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 2005,
    "club": "Chelsea",
    "siglaClub": "CHE",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "est": 82,
      "par": 88,
      "saq": 73,
      "ref": 98,
      "vel": 78,
      "col": 84
    },
    "ata": 26,
    "cre": 44,
    "def": 42,
    "arq": 88
  },
  {
    "id": 15,
    "nombre": "Jan Oblak",
    "nombreCarta": "Oblak",
    "pais": "Eslovenia",
    "bandera": "🇸🇮",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 2018,
    "club": "Atlético de Madrid",
    "siglaClub": "ATM",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "est": 82,
      "par": 88,
      "saq": 73,
      "ref": 98,
      "vel": 78,
      "col": 84
    },
    "ata": 26,
    "cre": 44,
    "def": 42,
    "arq": 88
  },
  {
    "id": 16,
    "nombre": "Ubaldo Fillol",
    "nombreCarta": "Fillol",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 1978,
    "club": "River Plate",
    "siglaClub": "RIV",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "est": 87,
      "par": 87,
      "saq": 81,
      "ref": 87,
      "vel": 81,
      "col": 87
    },
    "ata": 28,
    "cre": 49,
    "def": 44,
    "arq": 87
  },
  {
    "id": 17,
    "nombre": "Dibu Martínez",
    "nombreCarta": "Dibu",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 2022,
    "club": "Aston Villa",
    "siglaClub": "AVI",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "est": 81,
      "par": 87,
      "saq": 72,
      "ref": 97,
      "vel": 77,
      "col": 83
    },
    "ata": 25,
    "cre": 43,
    "def": 42,
    "arq": 87
  },
  {
    "id": 18,
    "nombre": "José Luis Chilavert",
    "nombreCarta": "Chilavert",
    "pais": "Paraguay",
    "bandera": "🇵🇾",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 1998,
    "club": "Vélez Sarsfield",
    "siglaClub": "VSA",
    "ovr": 86,
    "categoria": "Figura",
    "carta": {
      "est": 84,
      "par": 84,
      "saq": 99,
      "ref": 88,
      "vel": 82,
      "col": 88
    },
    "ata": 35,
    "cre": 59,
    "def": 44,
    "arq": 86
  },
  {
    "id": 19,
    "nombre": "Rinat Dasáyev",
    "nombreCarta": "Dasáyev",
    "pais": "Rusia",
    "bandera": "🇷🇺",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 1988,
    "club": "Spartak Moscú",
    "siglaClub": "SPM",
    "ovr": 86,
    "categoria": "Figura",
    "carta": {
      "est": 88,
      "par": 86,
      "saq": 70,
      "ref": 78,
      "vel": 72,
      "col": 92
    },
    "ata": 25,
    "cre": 42,
    "def": 46,
    "arq": 86
  },
  {
    "id": 20,
    "nombre": "Walter Zenga",
    "nombreCarta": "Zenga",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "POR",
    "posDetalle": "POR",
    "pico": 1990,
    "club": "Inter",
    "siglaClub": "INT",
    "ovr": 86,
    "categoria": "Figura",
    "carta": {
      "est": 80,
      "par": 86,
      "saq": 71,
      "ref": 96,
      "vel": 76,
      "col": 82
    },
    "ata": 25,
    "cre": 43,
    "def": 41,
    "arq": 86
  },
  {
    "id": 21,
    "nombre": "Franz Beckenbauer",
    "nombreCarta": "Beckenbauer",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1972,
    "club": "Bayern Múnich",
    "siglaClub": "BAY",
    "ovr": 97,
    "categoria": "Leyenda",
    "carta": {
      "rit": 99,
      "tir": 89,
      "pas": 99,
      "reg": 99,
      "def": 99,
      "fis": 89
    },
    "ata": 94,
    "cre": 99,
    "def": 97,
    "arq": 10
  },
  {
    "id": 22,
    "nombre": "Paolo Maldini",
    "nombreCarta": "Maldini",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1994,
    "club": "Milan",
    "siglaClub": "MIL",
    "ovr": 95,
    "categoria": "Leyenda",
    "carta": {
      "rit": 95,
      "tir": 89,
      "pas": 99,
      "reg": 95,
      "def": 94,
      "fis": 99
    },
    "ata": 92,
    "cre": 97,
    "def": 95,
    "arq": 10
  },
  {
    "id": 23,
    "nombre": "Franco Baresi",
    "nombreCarta": "Baresi",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1990,
    "club": "Milan",
    "siglaClub": "MIL",
    "ovr": 94,
    "categoria": "Crack",
    "carta": {
      "rit": 80,
      "tir": 55,
      "pas": 82,
      "reg": 80,
      "def": 96,
      "fis": 88
    },
    "ata": 68,
    "cre": 81,
    "def": 94,
    "arq": 10
  },
  {
    "id": 24,
    "nombre": "Bobby Moore",
    "nombreCarta": "Moore",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1966,
    "club": "West Ham United",
    "siglaClub": "WHU",
    "ovr": 92,
    "categoria": "Crack",
    "carta": {
      "rit": 82,
      "tir": 82,
      "pas": 94,
      "reg": 88,
      "def": 91,
      "fis": 94
    },
    "ata": 84,
    "cre": 92,
    "def": 92,
    "arq": 10
  },
  {
    "id": 25,
    "nombre": "Fabio Cannavaro",
    "nombreCarta": "Cannavaro",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 2006,
    "club": "Juventus",
    "siglaClub": "JUV",
    "ovr": 92,
    "categoria": "Crack",
    "carta": {
      "rit": 92,
      "tir": 86,
      "pas": 96,
      "reg": 92,
      "def": 91,
      "fis": 96
    },
    "ata": 89,
    "cre": 94,
    "def": 92,
    "arq": 10
  },
  {
    "id": 26,
    "nombre": "Daniel Passarella",
    "nombreCarta": "Passarella",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1978,
    "club": "River Plate",
    "siglaClub": "RIV",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 89,
      "tir": 87,
      "pas": 81,
      "reg": 83,
      "def": 88,
      "fis": 99
    },
    "ata": 86,
    "cre": 82,
    "def": 91,
    "arq": 10
  },
  {
    "id": 27,
    "nombre": "Sergio Ramos",
    "nombreCarta": "S. Ramos",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 2014,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 89,
      "tir": 87,
      "pas": 81,
      "reg": 83,
      "def": 88,
      "fis": 99
    },
    "ata": 86,
    "cre": 82,
    "def": 91,
    "arq": 10
  },
  {
    "id": 28,
    "nombre": "Virgil van Dijk",
    "nombreCarta": "Van Dijk",
    "pais": "Países Bajos",
    "bandera": "🇳🇱",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 2019,
    "club": "Liverpool",
    "siglaClub": "LIV",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 91,
      "tir": 85,
      "pas": 95,
      "reg": 91,
      "def": 90,
      "fis": 95
    },
    "ata": 88,
    "cre": 93,
    "def": 91,
    "arq": 10
  },
  {
    "id": 29,
    "nombre": "Carlos Alberto Torres",
    "nombreCarta": "C. Alberto",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEF",
    "posDetalle": "LD",
    "pico": 1970,
    "club": "Santos",
    "siglaClub": "SAN",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 80,
      "pas": 94,
      "reg": 96,
      "def": 93,
      "fis": 80
    },
    "ata": 89,
    "cre": 95,
    "def": 90,
    "arq": 10
  },
  {
    "id": 30,
    "nombre": "Cafu",
    "nombreCarta": "Cafu",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEF",
    "posDetalle": "LD",
    "pico": 2002,
    "club": "Roma",
    "siglaClub": "ROM",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 80,
      "pas": 94,
      "reg": 96,
      "def": 93,
      "fis": 80
    },
    "ata": 89,
    "cre": 95,
    "def": 90,
    "arq": 10
  },
  {
    "id": 31,
    "nombre": "Roberto Carlos",
    "nombreCarta": "R. Carlos",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEF",
    "posDetalle": "LI",
    "pico": 2002,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 99,
      "pas": 92,
      "reg": 98,
      "def": 92,
      "fis": 84
    },
    "ata": 99,
    "cre": 94,
    "def": 90,
    "arq": 10
  },
  {
    "id": 32,
    "nombre": "Elías Figueroa",
    "nombreCarta": "Figueroa",
    "pais": "Chile",
    "bandera": "🇨🇱",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1974,
    "club": "Internacional",
    "siglaClub": "INL",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 90,
      "tir": 84,
      "pas": 94,
      "reg": 90,
      "def": 89,
      "fis": 94
    },
    "ata": 87,
    "cre": 92,
    "def": 90,
    "arq": 10
  },
  {
    "id": 33,
    "nombre": "Giacinto Facchetti",
    "nombreCarta": "Facchetti",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "DEF",
    "posDetalle": "LI",
    "pico": 1965,
    "club": "Inter",
    "siglaClub": "INT",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 80,
      "pas": 94,
      "reg": 96,
      "def": 93,
      "fis": 80
    },
    "ata": 89,
    "cre": 95,
    "def": 90,
    "arq": 10
  },
  {
    "id": 34,
    "nombre": "Philipp Lahm",
    "nombreCarta": "Lahm",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "DEF",
    "posDetalle": "LD",
    "pico": 2014,
    "club": "Bayern Múnich",
    "siglaClub": "BAY",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 80,
      "pas": 94,
      "reg": 96,
      "def": 93,
      "fis": 80
    },
    "ata": 89,
    "cre": 95,
    "def": 90,
    "arq": 10
  },
  {
    "id": 35,
    "nombre": "Nílton Santos",
    "nombreCarta": "N. Santos",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEF",
    "posDetalle": "LI",
    "pico": 1958,
    "club": "Botafogo",
    "siglaClub": "BOT",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 80,
      "pas": 94,
      "reg": 96,
      "def": 93,
      "fis": 80
    },
    "ata": 89,
    "cre": 95,
    "def": 90,
    "arq": 10
  },
  {
    "id": 36,
    "nombre": "Gaetano Scirea",
    "nombreCarta": "Scirea",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1982,
    "club": "Juventus",
    "siglaClub": "JUV",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 94,
      "tir": 82,
      "pas": 99,
      "reg": 98,
      "def": 93,
      "fis": 82
    },
    "ata": 89,
    "cre": 99,
    "def": 90,
    "arq": 10
  },
  {
    "id": 37,
    "nombre": "Alessandro Nesta",
    "nombreCarta": "Nesta",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 2003,
    "club": "Milan",
    "siglaClub": "MIL",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 90,
      "tir": 84,
      "pas": 94,
      "reg": 90,
      "def": 89,
      "fis": 94
    },
    "ata": 87,
    "cre": 92,
    "def": 90,
    "arq": 10
  },
  {
    "id": 38,
    "nombre": "Ruud Krol",
    "nombreCarta": "Krol",
    "pais": "Países Bajos",
    "bandera": "🇳🇱",
    "posicion": "DEF",
    "posDetalle": "LI",
    "pico": 1974,
    "club": "Ajax",
    "siglaClub": "AJA",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 93,
      "tir": 81,
      "pas": 99,
      "reg": 97,
      "def": 92,
      "fis": 81
    },
    "ata": 88,
    "cre": 98,
    "def": 89,
    "arq": 10
  },
  {
    "id": 39,
    "nombre": "Carles Puyol",
    "nombreCarta": "Puyol",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 2010,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 87,
      "tir": 85,
      "pas": 79,
      "reg": 81,
      "def": 86,
      "fis": 99
    },
    "ata": 84,
    "cre": 80,
    "def": 89,
    "arq": 10
  },
  {
    "id": 40,
    "nombre": "Marcel Desailly",
    "nombreCarta": "Desailly",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1998,
    "club": "Milan",
    "siglaClub": "MIL",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 81,
      "tir": 75,
      "pas": 77,
      "reg": 77,
      "def": 86,
      "fis": 99
    },
    "ata": 77,
    "cre": 77,
    "def": 89,
    "arq": 10
  },
  {
    "id": 41,
    "nombre": "Lilian Thuram",
    "nombreCarta": "Thuram",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1998,
    "club": "Parma",
    "siglaClub": "PAR",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 89,
      "tir": 83,
      "pas": 93,
      "reg": 89,
      "def": 88,
      "fis": 93
    },
    "ata": 86,
    "cre": 91,
    "def": 89,
    "arq": 10
  },
  {
    "id": 42,
    "nombre": "Paul Breitner",
    "nombreCarta": "Breitner",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "DEF",
    "posDetalle": "LI",
    "pico": 1974,
    "club": "Bayern Múnich",
    "siglaClub": "BAY",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 92,
      "tir": 80,
      "pas": 99,
      "reg": 96,
      "def": 91,
      "fis": 80
    },
    "ata": 87,
    "cre": 98,
    "def": 88,
    "arq": 10
  },
  {
    "id": 43,
    "nombre": "Ronald Koeman",
    "nombreCarta": "Koeman",
    "pais": "Países Bajos",
    "bandera": "🇳🇱",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1992,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 92,
      "tir": 80,
      "pas": 99,
      "reg": 96,
      "def": 91,
      "fis": 80
    },
    "ata": 87,
    "cre": 98,
    "def": 88,
    "arq": 10
  },
  {
    "id": 44,
    "nombre": "Djalma Santos",
    "nombreCarta": "D. Santos",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEF",
    "posDetalle": "LD",
    "pico": 1958,
    "club": "Portuguesa",
    "siglaClub": "PTG",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 99,
      "tir": 78,
      "pas": 92,
      "reg": 94,
      "def": 91,
      "fis": 78
    },
    "ata": 87,
    "cre": 93,
    "def": 88,
    "arq": 10
  },
  {
    "id": 45,
    "nombre": "Rio Ferdinand",
    "nombreCarta": "Ferdinand",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 2008,
    "club": "Manchester United",
    "siglaClub": "MUN",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 88,
      "tir": 82,
      "pas": 92,
      "reg": 88,
      "def": 87,
      "fis": 92
    },
    "ata": 85,
    "cre": 90,
    "def": 88,
    "arq": 10
  },
  {
    "id": 46,
    "nombre": "John Terry",
    "nombreCarta": "Terry",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 2005,
    "club": "Chelsea",
    "siglaClub": "CHE",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 86,
      "tir": 84,
      "pas": 78,
      "reg": 80,
      "def": 85,
      "fis": 98
    },
    "ata": 83,
    "cre": 79,
    "def": 88,
    "arq": 10
  },
  {
    "id": 47,
    "nombre": "Javier Zanetti",
    "nombreCarta": "Zanetti",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEF",
    "posDetalle": "LD",
    "pico": 2010,
    "club": "Inter",
    "siglaClub": "INT",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 99,
      "tir": 78,
      "pas": 92,
      "reg": 94,
      "def": 91,
      "fis": 78
    },
    "ata": 87,
    "cre": 93,
    "def": 88,
    "arq": 10
  },
  {
    "id": 48,
    "nombre": "Thiago Silva",
    "nombreCarta": "T. Silva",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 2013,
    "club": "Paris Saint-Germain",
    "siglaClub": "PSG",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 88,
      "tir": 82,
      "pas": 92,
      "reg": 88,
      "def": 87,
      "fis": 92
    },
    "ata": 85,
    "cre": 90,
    "def": 88,
    "arq": 10
  },
  {
    "id": 49,
    "nombre": "Dani Alves",
    "nombreCarta": "Dani Alves",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEF",
    "posDetalle": "LD",
    "pico": 2011,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 99,
      "tir": 78,
      "pas": 92,
      "reg": 94,
      "def": 91,
      "fis": 78
    },
    "ata": 87,
    "cre": 93,
    "def": 88,
    "arq": 10
  },
  {
    "id": 50,
    "nombre": "Gerard Piqué",
    "nombreCarta": "Piqué",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 2011,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 87,
      "tir": 81,
      "pas": 91,
      "reg": 87,
      "def": 86,
      "fis": 91
    },
    "ata": 84,
    "cre": 89,
    "def": 87,
    "arq": 10
  },
  {
    "id": 51,
    "nombre": "Claudio Gentile",
    "nombreCarta": "Gentile",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "DEF",
    "posDetalle": "LD",
    "pico": 1982,
    "club": "Juventus",
    "siglaClub": "JUV",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 79,
      "tir": 73,
      "pas": 75,
      "reg": 75,
      "def": 83,
      "fis": 99
    },
    "ata": 75,
    "cre": 75,
    "def": 87,
    "arq": 10
  },
  {
    "id": 52,
    "nombre": "Andreas Brehme",
    "nombreCarta": "Brehme",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "DEF",
    "posDetalle": "LI",
    "pico": 1990,
    "club": "Inter",
    "siglaClub": "INT",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 99,
      "tir": 77,
      "pas": 91,
      "reg": 93,
      "def": 90,
      "fis": 77
    },
    "ata": 86,
    "cre": 92,
    "def": 87,
    "arq": 10
  },
  {
    "id": 53,
    "nombre": "José Santamaría",
    "nombreCarta": "Santamaría",
    "pais": "Uruguay",
    "bandera": "🇺🇾",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1959,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 79,
      "tir": 73,
      "pas": 75,
      "reg": 75,
      "def": 83,
      "fis": 99
    },
    "ata": 75,
    "cre": 75,
    "def": 87,
    "arq": 10
  },
  {
    "id": 54,
    "nombre": "Laurent Blanc",
    "nombreCarta": "Blanc",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1998,
    "club": "Olympique de Marsella",
    "siglaClub": "OMA",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 91,
      "tir": 79,
      "pas": 99,
      "reg": 95,
      "def": 90,
      "fis": 79
    },
    "ata": 86,
    "cre": 97,
    "def": 87,
    "arq": 10
  },
  {
    "id": 55,
    "nombre": "Fernando Hierro",
    "nombreCarta": "Hierro",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1998,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 79,
      "tir": 73,
      "pas": 75,
      "reg": 75,
      "def": 83,
      "fis": 99
    },
    "ata": 75,
    "cre": 75,
    "def": 87,
    "arq": 10
  },
  {
    "id": 56,
    "nombre": "Nemanja Vidić",
    "nombreCarta": "Vidić",
    "pais": "Serbia",
    "bandera": "🇷🇸",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 2009,
    "club": "Manchester United",
    "siglaClub": "MUN",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 79,
      "tir": 73,
      "pas": 75,
      "reg": 75,
      "def": 83,
      "fis": 99
    },
    "ata": 75,
    "cre": 75,
    "def": 87,
    "arq": 10
  },
  {
    "id": 57,
    "nombre": "Jaap Stam",
    "nombreCarta": "Stam",
    "pais": "Países Bajos",
    "bandera": "🇳🇱",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1999,
    "club": "Manchester United",
    "siglaClub": "MUN",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 79,
      "tir": 73,
      "pas": 75,
      "reg": 75,
      "def": 83,
      "fis": 99
    },
    "ata": 75,
    "cre": 75,
    "def": 87,
    "arq": 10
  },
  {
    "id": 58,
    "nombre": "Mats Hummels",
    "nombreCarta": "Hummels",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 2014,
    "club": "Borussia Dortmund",
    "siglaClub": "BVB",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 91,
      "tir": 79,
      "pas": 99,
      "reg": 95,
      "def": 90,
      "fis": 79
    },
    "ata": 86,
    "cre": 97,
    "def": 87,
    "arq": 10
  },
  {
    "id": 59,
    "nombre": "Marcelo",
    "nombreCarta": "Marcelo",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEF",
    "posDetalle": "LI",
    "pico": 2017,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 99,
      "tir": 77,
      "pas": 91,
      "reg": 93,
      "def": 90,
      "fis": 77
    },
    "ata": 86,
    "cre": 92,
    "def": 87,
    "arq": 10
  },
  {
    "id": 60,
    "nombre": "Diego Godín",
    "nombreCarta": "Godín",
    "pais": "Uruguay",
    "bandera": "🇺🇾",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 2014,
    "club": "Atlético de Madrid",
    "siglaClub": "ATM",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 85,
      "tir": 83,
      "pas": 77,
      "reg": 79,
      "def": 84,
      "fis": 97
    },
    "ata": 82,
    "cre": 78,
    "def": 87,
    "arq": 10
  },
  {
    "id": 61,
    "nombre": "Oscar Ruggeri",
    "nombreCarta": "Ruggeri",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1986,
    "club": "River Plate",
    "siglaClub": "RIV",
    "ovr": 86,
    "categoria": "Figura",
    "carta": {
      "rit": 84,
      "tir": 82,
      "pas": 76,
      "reg": 78,
      "def": 83,
      "fis": 96
    },
    "ata": 81,
    "cre": 77,
    "def": 86,
    "arq": 10
  },
  {
    "id": 62,
    "nombre": "Roberto Perfumo",
    "nombreCarta": "Perfumo",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1967,
    "club": "Racing Club",
    "siglaClub": "RAC",
    "ovr": 86,
    "categoria": "Figura",
    "carta": {
      "rit": 86,
      "tir": 80,
      "pas": 90,
      "reg": 86,
      "def": 85,
      "fis": 90
    },
    "ata": 83,
    "cre": 88,
    "def": 86,
    "arq": 10
  },
  {
    "id": 63,
    "nombre": "Silvio Marzolini",
    "nombreCarta": "Marzolini",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEF",
    "posDetalle": "LI",
    "pico": 1966,
    "club": "Boca Juniors",
    "siglaClub": "BOC",
    "ovr": 86,
    "categoria": "Figura",
    "carta": {
      "rit": 99,
      "tir": 76,
      "pas": 90,
      "reg": 92,
      "def": 89,
      "fis": 76
    },
    "ata": 85,
    "cre": 91,
    "def": 86,
    "arq": 10
  },
  {
    "id": 64,
    "nombre": "Rafael Márquez",
    "nombreCarta": "Márquez",
    "pais": "México",
    "bandera": "🇲🇽",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 2006,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 85,
    "categoria": "Figura",
    "carta": {
      "rit": 85,
      "tir": 79,
      "pas": 89,
      "reg": 85,
      "def": 84,
      "fis": 89
    },
    "ata": 82,
    "cre": 87,
    "def": 85,
    "arq": 10
  },
  {
    "id": 65,
    "nombre": "Héctor Chumpitaz",
    "nombreCarta": "Chumpitaz",
    "pais": "Perú",
    "bandera": "🇵🇪",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 1970,
    "club": "Universitario",
    "siglaClub": "UNI",
    "ovr": 85,
    "categoria": "Figura",
    "carta": {
      "rit": 83,
      "tir": 81,
      "pas": 75,
      "reg": 77,
      "def": 82,
      "fis": 95
    },
    "ata": 80,
    "cre": 76,
    "def": 85,
    "arq": 10
  },
  {
    "id": 66,
    "nombre": "Roberto Ayala",
    "nombreCarta": "Ayala",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEF",
    "posDetalle": "DFC",
    "pico": 2002,
    "club": "Valencia",
    "siglaClub": "VAL",
    "ovr": 85,
    "categoria": "Figura",
    "carta": {
      "rit": 85,
      "tir": 79,
      "pas": 89,
      "reg": 85,
      "def": 84,
      "fis": 89
    },
    "ata": 82,
    "cre": 87,
    "def": 85,
    "arq": 10
  },
  {
    "id": 67,
    "nombre": "Diego Maradona",
    "nombreCarta": "Maradona",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1986,
    "club": "Napoli",
    "siglaClub": "NAP",
    "ovr": 99,
    "categoria": "Leyenda",
    "carta": {
      "rit": 95,
      "tir": 99,
      "pas": 99,
      "reg": 99,
      "def": 79,
      "fis": 89
    },
    "ata": 98,
    "cre": 99,
    "def": 82,
    "arq": 10
  },
  {
    "id": 68,
    "nombre": "Zinedine Zidane",
    "nombreCarta": "Zidane",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1998,
    "club": "Juventus",
    "siglaClub": "JUV",
    "ovr": 96,
    "categoria": "Leyenda",
    "carta": {
      "rit": 92,
      "tir": 99,
      "pas": 94,
      "reg": 99,
      "def": 76,
      "fis": 86
    },
    "ata": 98,
    "cre": 96,
    "def": 79,
    "arq": 10
  },
  {
    "id": 69,
    "nombre": "Michel Platini",
    "nombreCarta": "Platini",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1984,
    "club": "Juventus",
    "siglaClub": "JUV",
    "ovr": 95,
    "categoria": "Leyenda",
    "carta": {
      "rit": 91,
      "tir": 99,
      "pas": 92,
      "reg": 99,
      "def": 75,
      "fis": 85
    },
    "ata": 97,
    "cre": 95,
    "def": 78,
    "arq": 10
  },
  {
    "id": 70,
    "nombre": "Ronaldinho",
    "nombreCarta": "Ronaldinho",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 2005,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 95,
    "categoria": "Leyenda",
    "carta": {
      "rit": 91,
      "tir": 99,
      "pas": 92,
      "reg": 99,
      "def": 75,
      "fis": 85
    },
    "ata": 97,
    "cre": 95,
    "def": 78,
    "arq": 10
  },
  {
    "id": 71,
    "nombre": "Zico",
    "nombreCarta": "Zico",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1981,
    "club": "Flamengo",
    "siglaClub": "FLA",
    "ovr": 94,
    "categoria": "Crack",
    "carta": {
      "rit": 90,
      "tir": 99,
      "pas": 91,
      "reg": 99,
      "def": 74,
      "fis": 84
    },
    "ata": 97,
    "cre": 94,
    "def": 77,
    "arq": 10
  },
  {
    "id": 72,
    "nombre": "Xavi Hernández",
    "nombreCarta": "Xavi",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 2011,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 93,
    "categoria": "Crack",
    "carta": {
      "rit": 83,
      "tir": 85,
      "pas": 98,
      "reg": 85,
      "def": 68,
      "fis": 89
    },
    "ata": 85,
    "cre": 93,
    "def": 73,
    "arq": 10
  },
  {
    "id": 73,
    "nombre": "Andrés Iniesta",
    "nombreCarta": "Iniesta",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 2012,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 93,
    "categoria": "Crack",
    "carta": {
      "rit": 89,
      "tir": 99,
      "pas": 89,
      "reg": 99,
      "def": 73,
      "fis": 83
    },
    "ata": 97,
    "cre": 93,
    "def": 76,
    "arq": 10
  },
  {
    "id": 74,
    "nombre": "Lothar Matthäus",
    "nombreCarta": "Matthäus",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 1990,
    "club": "Inter",
    "siglaClub": "INT",
    "ovr": 93,
    "categoria": "Crack",
    "carta": {
      "rit": 99,
      "tir": 95,
      "pas": 93,
      "reg": 93,
      "def": 83,
      "fis": 99
    },
    "ata": 95,
    "cre": 93,
    "def": 87,
    "arq": 10
  },
  {
    "id": 75,
    "nombre": "Bobby Charlton",
    "nombreCarta": "Charlton",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 1966,
    "club": "Manchester United",
    "siglaClub": "MUN",
    "ovr": 93,
    "categoria": "Crack",
    "carta": {
      "rit": 99,
      "tir": 95,
      "pas": 93,
      "reg": 93,
      "def": 83,
      "fis": 99
    },
    "ata": 95,
    "cre": 93,
    "def": 87,
    "arq": 10
  },
  {
    "id": 76,
    "nombre": "Luka Modrić",
    "nombreCarta": "Modrić",
    "pais": "Croacia",
    "bandera": "🇭🇷",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 2018,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 92,
    "categoria": "Crack",
    "carta": {
      "rit": 82,
      "tir": 84,
      "pas": 97,
      "reg": 84,
      "def": 67,
      "fis": 88
    },
    "ata": 84,
    "cre": 92,
    "def": 72,
    "arq": 10
  },
  {
    "id": 77,
    "nombre": "Kaká",
    "nombreCarta": "Kaká",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 2007,
    "club": "Milan",
    "siglaClub": "MIL",
    "ovr": 92,
    "categoria": "Crack",
    "carta": {
      "rit": 99,
      "tir": 94,
      "pas": 92,
      "reg": 92,
      "def": 82,
      "fis": 99
    },
    "ata": 94,
    "cre": 92,
    "def": 86,
    "arq": 10
  },
  {
    "id": 78,
    "nombre": "Ruud Gullit",
    "nombreCarta": "Gullit",
    "pais": "Países Bajos",
    "bandera": "🇳🇱",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 1988,
    "club": "Milan",
    "siglaClub": "MIL",
    "ovr": 92,
    "categoria": "Crack",
    "carta": {
      "rit": 99,
      "tir": 94,
      "pas": 92,
      "reg": 92,
      "def": 82,
      "fis": 99
    },
    "ata": 94,
    "cre": 92,
    "def": 86,
    "arq": 10
  },
  {
    "id": 79,
    "nombre": "Didi",
    "nombreCarta": "Didi",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 1958,
    "club": "Botafogo",
    "siglaClub": "BOT",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 81,
      "tir": 83,
      "pas": 96,
      "reg": 83,
      "def": 66,
      "fis": 87
    },
    "ata": 83,
    "cre": 91,
    "def": 71,
    "arq": 10
  },
  {
    "id": 80,
    "nombre": "Frank Rijkaard",
    "nombreCarta": "Rijkaard",
    "pais": "Países Bajos",
    "bandera": "🇳🇱",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 1989,
    "club": "Milan",
    "siglaClub": "MIL",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 93,
      "pas": 91,
      "reg": 91,
      "def": 81,
      "fis": 99
    },
    "ata": 94,
    "cre": 91,
    "def": 86,
    "arq": 10
  },
  {
    "id": 81,
    "nombre": "Andrea Pirlo",
    "nombreCarta": "Pirlo",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "MED",
    "posDetalle": "MCD",
    "pico": 2006,
    "club": "Milan",
    "siglaClub": "MIL",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 81,
      "tir": 83,
      "pas": 96,
      "reg": 83,
      "def": 66,
      "fis": 87
    },
    "ata": 83,
    "cre": 91,
    "def": 71,
    "arq": 10
  },
  {
    "id": 82,
    "nombre": "Kevin De Bruyne",
    "nombreCarta": "De Bruyne",
    "pais": "Bélgica",
    "bandera": "🇧🇪",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 2020,
    "club": "Manchester City",
    "siglaClub": "MCI",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 93,
      "pas": 91,
      "reg": 91,
      "def": 81,
      "fis": 99
    },
    "ata": 94,
    "cre": 91,
    "def": 86,
    "arq": 10
  },
  {
    "id": 83,
    "nombre": "Gianni Rivera",
    "nombreCarta": "Rivera",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1969,
    "club": "Milan",
    "siglaClub": "MIL",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 87,
      "tir": 99,
      "pas": 86,
      "reg": 99,
      "def": 71,
      "fis": 81
    },
    "ata": 97,
    "cre": 91,
    "def": 74,
    "arq": 10
  },
  {
    "id": 84,
    "nombre": "Sócrates",
    "nombreCarta": "Sócrates",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1982,
    "club": "Corinthians",
    "siglaClub": "COR",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 87,
      "tir": 99,
      "pas": 86,
      "reg": 99,
      "def": 71,
      "fis": 81
    },
    "ata": 97,
    "cre": 91,
    "def": 74,
    "arq": 10
  },
  {
    "id": 85,
    "nombre": "Rivelino",
    "nombreCarta": "Rivelino",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "MED",
    "posDetalle": "MI",
    "pico": 1970,
    "club": "Corinthians",
    "siglaClub": "COR",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 87,
      "tir": 99,
      "pas": 86,
      "reg": 99,
      "def": 71,
      "fis": 81
    },
    "ata": 97,
    "cre": 91,
    "def": 74,
    "arq": 10
  },
  {
    "id": 86,
    "nombre": "Juan Alberto Schiaffino",
    "nombreCarta": "Schiaffino",
    "pais": "Uruguay",
    "bandera": "🇺🇾",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1950,
    "club": "Peñarol",
    "siglaClub": "PEN",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 87,
      "tir": 99,
      "pas": 86,
      "reg": 99,
      "def": 71,
      "fis": 81
    },
    "ata": 97,
    "cre": 91,
    "def": 74,
    "arq": 10
  },
  {
    "id": 87,
    "nombre": "Luis Figo",
    "nombreCarta": "Figo",
    "pais": "Portugal",
    "bandera": "🇵🇹",
    "posicion": "MED",
    "posDetalle": "MD",
    "pico": 2000,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 95,
      "pas": 86,
      "reg": 99,
      "def": 69,
      "fis": 85
    },
    "ata": 97,
    "cre": 91,
    "def": 73,
    "arq": 10
  },
  {
    "id": 88,
    "nombre": "Zizinho",
    "nombreCarta": "Zizinho",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1950,
    "club": "Bangu",
    "siglaClub": "BAN",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 86,
      "tir": 98,
      "pas": 84,
      "reg": 99,
      "def": 70,
      "fis": 80
    },
    "ata": 96,
    "cre": 90,
    "def": 73,
    "arq": 10
  },
  {
    "id": 89,
    "nombre": "Johan Neeskens",
    "nombreCarta": "Neeskens",
    "pais": "Países Bajos",
    "bandera": "🇳🇱",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 1974,
    "club": "Ajax",
    "siglaClub": "AJA",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 98,
      "tir": 92,
      "pas": 90,
      "reg": 90,
      "def": 80,
      "fis": 98
    },
    "ata": 93,
    "cre": 90,
    "def": 85,
    "arq": 10
  },
  {
    "id": 90,
    "nombre": "Toni Kroos",
    "nombreCarta": "Kroos",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 2017,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 80,
      "tir": 82,
      "pas": 95,
      "reg": 82,
      "def": 65,
      "fis": 86
    },
    "ata": 82,
    "cre": 90,
    "def": 70,
    "arq": 10
  },
  {
    "id": 91,
    "nombre": "Steven Gerrard",
    "nombreCarta": "Gerrard",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 2005,
    "club": "Liverpool",
    "siglaClub": "LIV",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 98,
      "tir": 92,
      "pas": 90,
      "reg": 90,
      "def": 80,
      "fis": 98
    },
    "ata": 93,
    "cre": 90,
    "def": 85,
    "arq": 10
  },
  {
    "id": 92,
    "nombre": "Pavel Nedvěd",
    "nombreCarta": "Nedvěd",
    "pais": "Chequia",
    "bandera": "🇨🇿",
    "posicion": "MED",
    "posDetalle": "MI",
    "pico": 2003,
    "club": "Juventus",
    "siglaClub": "JUV",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 98,
      "tir": 92,
      "pas": 90,
      "reg": 90,
      "def": 80,
      "fis": 98
    },
    "ata": 93,
    "cre": 90,
    "def": 85,
    "arq": 10
  },
  {
    "id": 93,
    "nombre": "Falcão",
    "nombreCarta": "Falcão",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 1982,
    "club": "Roma",
    "siglaClub": "ROM",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 98,
      "tir": 92,
      "pas": 90,
      "reg": 90,
      "def": 80,
      "fis": 98
    },
    "ata": 93,
    "cre": 90,
    "def": 85,
    "arq": 10
  },
  {
    "id": 94,
    "nombre": "Rodri",
    "nombreCarta": "Rodri",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "MED",
    "posDetalle": "MCD",
    "pico": 2024,
    "club": "Manchester City",
    "siglaClub": "MCI",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 80,
      "tir": 82,
      "pas": 95,
      "reg": 82,
      "def": 65,
      "fis": 86
    },
    "ata": 82,
    "cre": 90,
    "def": 70,
    "arq": 10
  },
  {
    "id": 95,
    "nombre": "Luis Suárez Miramontes",
    "nombreCarta": "L. Suárez M.",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 1960,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 86,
      "tir": 98,
      "pas": 84,
      "reg": 99,
      "def": 70,
      "fis": 80
    },
    "ata": 96,
    "cre": 90,
    "def": 73,
    "arq": 10
  },
  {
    "id": 96,
    "nombre": "Fritz Walter",
    "nombreCarta": "F. Walter",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1954,
    "club": "Kaiserslautern",
    "siglaClub": "FCK",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 86,
      "tir": 98,
      "pas": 84,
      "reg": 99,
      "def": 70,
      "fis": 80
    },
    "ata": 96,
    "cre": 90,
    "def": 73,
    "arq": 10
  },
  {
    "id": 97,
    "nombre": "Michael Laudrup",
    "nombreCarta": "Laudrup",
    "pais": "Dinamarca",
    "bandera": "🇩🇰",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1992,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 86,
      "tir": 98,
      "pas": 84,
      "reg": 99,
      "def": 70,
      "fis": 80
    },
    "ata": 96,
    "cre": 90,
    "def": 73,
    "arq": 10
  },
  {
    "id": 98,
    "nombre": "Gérson",
    "nombreCarta": "Gérson",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 1970,
    "club": "São Paulo",
    "siglaClub": "SAO",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 79,
      "tir": 81,
      "pas": 94,
      "reg": 81,
      "def": 64,
      "fis": 85
    },
    "ata": 81,
    "cre": 89,
    "def": 69,
    "arq": 10
  },
  {
    "id": 99,
    "nombre": "Sandro Mazzola",
    "nombreCarta": "Mazzola",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1965,
    "club": "Inter",
    "siglaClub": "INT",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 97,
      "tir": 91,
      "pas": 89,
      "reg": 89,
      "def": 79,
      "fis": 97
    },
    "ata": 92,
    "cre": 89,
    "def": 84,
    "arq": 10
  },
  {
    "id": 100,
    "nombre": "Günter Netzer",
    "nombreCarta": "Netzer",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 1972,
    "club": "Borussia Mönchengladbach",
    "siglaClub": "BMG",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 79,
      "tir": 81,
      "pas": 94,
      "reg": 81,
      "def": 64,
      "fis": 85
    },
    "ata": 81,
    "cre": 89,
    "def": 69,
    "arq": 10
  },
  {
    "id": 101,
    "nombre": "Fernando Redondo",
    "nombreCarta": "Redondo",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "MED",
    "posDetalle": "MCD",
    "pico": 2000,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 79,
      "tir": 81,
      "pas": 94,
      "reg": 81,
      "def": 64,
      "fis": 85
    },
    "ata": 81,
    "cre": 89,
    "def": 69,
    "arq": 10
  },
  {
    "id": 102,
    "nombre": "Juan Román Riquelme",
    "nombreCarta": "Riquelme",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 2001,
    "club": "Boca Juniors",
    "siglaClub": "BOC",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 66,
      "tir": 84,
      "pas": 90,
      "reg": 88,
      "def": 42,
      "fis": 75
    },
    "ata": 82,
    "cre": 89,
    "def": 50,
    "arq": 10
  },
  {
    "id": 103,
    "nombre": "Enzo Francescoli",
    "nombreCarta": "Francescoli",
    "pais": "Uruguay",
    "bandera": "🇺🇾",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1996,
    "club": "River Plate",
    "siglaClub": "RIV",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 85,
      "tir": 97,
      "pas": 82,
      "reg": 99,
      "def": 69,
      "fis": 79
    },
    "ata": 95,
    "cre": 89,
    "def": 72,
    "arq": 10
  },
  {
    "id": 104,
    "nombre": "Patrick Vieira",
    "nombreCarta": "Vieira",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "MED",
    "posDetalle": "MCD",
    "pico": 2004,
    "club": "Arsenal",
    "siglaClub": "ARS",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 87,
      "tir": 73,
      "pas": 73,
      "reg": 75,
      "def": 86,
      "fis": 99
    },
    "ata": 76,
    "cre": 74,
    "def": 89,
    "arq": 10
  },
  {
    "id": 105,
    "nombre": "Frank Lampard",
    "nombreCarta": "Lampard",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 2010,
    "club": "Chelsea",
    "siglaClub": "CHE",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 97,
      "tir": 91,
      "pas": 89,
      "reg": 89,
      "def": 79,
      "fis": 97
    },
    "ata": 92,
    "cre": 89,
    "def": 84,
    "arq": 10
  },
  {
    "id": 106,
    "nombre": "Sergio Busquets",
    "nombreCarta": "Busquets",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "MED",
    "posDetalle": "MCD",
    "pico": 2011,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 79,
      "tir": 81,
      "pas": 94,
      "reg": 81,
      "def": 64,
      "fis": 85
    },
    "ata": 81,
    "cre": 89,
    "def": 69,
    "arq": 10
  },
  {
    "id": 107,
    "nombre": "Michael Ballack",
    "nombreCarta": "Ballack",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 2002,
    "club": "Bayer Leverkusen",
    "siglaClub": "BLV",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 97,
      "tir": 91,
      "pas": 89,
      "reg": 89,
      "def": 79,
      "fis": 97
    },
    "ata": 92,
    "cre": 89,
    "def": 84,
    "arq": 10
  },
  {
    "id": 108,
    "nombre": "Josef Masopust",
    "nombreCarta": "Masopust",
    "pais": "Chequia",
    "bandera": "🇨🇿",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 1962,
    "club": "Dukla Praga",
    "siglaClub": "DUK",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 97,
      "tir": 91,
      "pas": 89,
      "reg": 89,
      "def": 79,
      "fis": 97
    },
    "ata": 92,
    "cre": 89,
    "def": 84,
    "arq": 10
  },
  {
    "id": 109,
    "nombre": "József Bozsik",
    "nombreCarta": "Bozsik",
    "pais": "Hungría",
    "bandera": "🇭🇺",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 1954,
    "club": "Honvéd",
    "siglaClub": "HON",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 79,
      "tir": 81,
      "pas": 94,
      "reg": 81,
      "def": 64,
      "fis": 85
    },
    "ata": 81,
    "cre": 89,
    "def": 69,
    "arq": 10
  },
  {
    "id": 110,
    "nombre": "Nándor Hidegkuti",
    "nombreCarta": "Hidegkuti",
    "pais": "Hungría",
    "bandera": "🇭🇺",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1953,
    "club": "MTK Budapest",
    "siglaClub": "MTK",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 85,
      "tir": 97,
      "pas": 82,
      "reg": 99,
      "def": 69,
      "fis": 79
    },
    "ata": 95,
    "cre": 89,
    "def": 72,
    "arq": 10
  },
  {
    "id": 111,
    "nombre": "Teófilo Cubillas",
    "nombreCarta": "Cubillas",
    "pais": "Perú",
    "bandera": "🇵🇪",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1970,
    "club": "Alianza Lima",
    "siglaClub": "ALI",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 84,
      "tir": 96,
      "pas": 81,
      "reg": 99,
      "def": 68,
      "fis": 78
    },
    "ata": 95,
    "cre": 88,
    "def": 71,
    "arq": 10
  },
  {
    "id": 112,
    "nombre": "Carlos Valderrama",
    "nombreCarta": "Valderrama",
    "pais": "Colombia",
    "bandera": "🇨🇴",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 1990,
    "club": "Montpellier",
    "siglaClub": "MTP",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 78,
      "tir": 80,
      "pas": 93,
      "reg": 80,
      "def": 63,
      "fis": 84
    },
    "ata": 80,
    "cre": 88,
    "def": 68,
    "arq": 10
  },
  {
    "id": 113,
    "nombre": "Gheorghe Hagi",
    "nombreCarta": "Hagi",
    "pais": "Rumania",
    "bandera": "🇷🇴",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1994,
    "club": "Brescia",
    "siglaClub": "BRE",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 84,
      "tir": 96,
      "pas": 81,
      "reg": 99,
      "def": 68,
      "fis": 78
    },
    "ata": 95,
    "cre": 88,
    "def": 71,
    "arq": 10
  },
  {
    "id": 114,
    "nombre": "Wesley Sneijder",
    "nombreCarta": "Sneijder",
    "pais": "Países Bajos",
    "bandera": "🇳🇱",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 2010,
    "club": "Inter",
    "siglaClub": "INT",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 84,
      "tir": 96,
      "pas": 81,
      "reg": 99,
      "def": 68,
      "fis": 78
    },
    "ata": 95,
    "cre": 88,
    "def": 71,
    "arq": 10
  },
  {
    "id": 115,
    "nombre": "Bastian Schweinsteiger",
    "nombreCarta": "Schweini",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 2013,
    "club": "Bayern Múnich",
    "siglaClub": "BAY",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 96,
      "tir": 90,
      "pas": 88,
      "reg": 88,
      "def": 78,
      "fis": 96
    },
    "ata": 91,
    "cre": 88,
    "def": 83,
    "arq": 10
  },
  {
    "id": 116,
    "nombre": "Paul Scholes",
    "nombreCarta": "Scholes",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 2007,
    "club": "Manchester United",
    "siglaClub": "MUN",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 78,
      "tir": 80,
      "pas": 93,
      "reg": 80,
      "def": 63,
      "fis": 84
    },
    "ata": 80,
    "cre": 88,
    "def": 68,
    "arq": 10
  },
  {
    "id": 117,
    "nombre": "David Silva",
    "nombreCarta": "D. Silva",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 2012,
    "club": "Manchester City",
    "siglaClub": "MCI",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 84,
      "tir": 96,
      "pas": 81,
      "reg": 99,
      "def": 68,
      "fis": 78
    },
    "ata": 95,
    "cre": 88,
    "def": 71,
    "arq": 10
  },
  {
    "id": 118,
    "nombre": "Deco",
    "nombreCarta": "Deco",
    "pais": "Portugal",
    "bandera": "🇵🇹",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 2004,
    "club": "Porto",
    "siglaClub": "FCP",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 84,
      "tir": 96,
      "pas": 81,
      "reg": 99,
      "def": 68,
      "fis": 78
    },
    "ata": 95,
    "cre": 88,
    "def": 71,
    "arq": 10
  },
  {
    "id": 119,
    "nombre": "Mário Coluna",
    "nombreCarta": "Coluna",
    "pais": "Portugal",
    "bandera": "🇵🇹",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 1962,
    "club": "Benfica",
    "siglaClub": "BEN",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 96,
      "tir": 90,
      "pas": 88,
      "reg": 88,
      "def": 78,
      "fis": 96
    },
    "ata": 91,
    "cre": 88,
    "def": 83,
    "arq": 10
  },
  {
    "id": 120,
    "nombre": "N'Golo Kanté",
    "nombreCarta": "Kanté",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "MED",
    "posDetalle": "MCD",
    "pico": 2017,
    "club": "Chelsea",
    "siglaClub": "CHE",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 86,
      "tir": 72,
      "pas": 72,
      "reg": 74,
      "def": 84,
      "fis": 99
    },
    "ata": 75,
    "cre": 73,
    "def": 88,
    "arq": 10
  },
  {
    "id": 121,
    "nombre": "Yaya Touré",
    "nombreCarta": "Yaya Touré",
    "pais": "Costa de Marfil",
    "bandera": "🇨🇮",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 2014,
    "club": "Manchester City",
    "siglaClub": "MCI",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 96,
      "tir": 90,
      "pas": 88,
      "reg": 88,
      "def": 78,
      "fis": 96
    },
    "ata": 91,
    "cre": 88,
    "def": 83,
    "arq": 10
  },
  {
    "id": 122,
    "nombre": "Obdulio Varela",
    "nombreCarta": "Varela",
    "pais": "Uruguay",
    "bandera": "🇺🇾",
    "posicion": "MED",
    "posDetalle": "MCD",
    "pico": 1950,
    "club": "Peñarol",
    "siglaClub": "PEN",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 86,
      "tir": 72,
      "pas": 72,
      "reg": 74,
      "def": 84,
      "fis": 99
    },
    "ata": 75,
    "cre": 73,
    "def": 88,
    "arq": 10
  },
  {
    "id": 123,
    "nombre": "Paul Gascoigne",
    "nombreCarta": "Gascoigne",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1990,
    "club": "Tottenham Hotspur",
    "siglaClub": "TOT",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 84,
      "tir": 96,
      "pas": 81,
      "reg": 99,
      "def": 68,
      "fis": 78
    },
    "ata": 95,
    "cre": 88,
    "def": 71,
    "arq": 10
  },
  {
    "id": 124,
    "nombre": "David Beckham",
    "nombreCarta": "Beckham",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "MED",
    "posDetalle": "MD",
    "pico": 1999,
    "club": "Manchester United",
    "siglaClub": "MUN",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 99,
      "tir": 92,
      "pas": 81,
      "reg": 99,
      "def": 66,
      "fis": 82
    },
    "ata": 96,
    "cre": 88,
    "def": 70,
    "arq": 10
  },
  {
    "id": 125,
    "nombre": "Ángel Di María",
    "nombreCarta": "Di María",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "MED",
    "posDetalle": "MI",
    "pico": 2014,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 99,
      "tir": 92,
      "pas": 81,
      "reg": 99,
      "def": 66,
      "fis": 82
    },
    "ata": 96,
    "cre": 88,
    "def": 70,
    "arq": 10
  },
  {
    "id": 126,
    "nombre": "Claude Makélélé",
    "nombreCarta": "Makélélé",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "MED",
    "posDetalle": "MCD",
    "pico": 2003,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 85,
      "tir": 71,
      "pas": 71,
      "reg": 73,
      "def": 83,
      "fis": 99
    },
    "ata": 74,
    "cre": 72,
    "def": 87,
    "arq": 10
  },
  {
    "id": 127,
    "nombre": "Juan Sebastián Verón",
    "nombreCarta": "Verón",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "MED",
    "posDetalle": "MC",
    "pico": 2001,
    "club": "Lazio",
    "siglaClub": "LAZ",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 95,
      "tir": 89,
      "pas": 87,
      "reg": 87,
      "def": 77,
      "fis": 95
    },
    "ata": 90,
    "cre": 87,
    "def": 82,
    "arq": 10
  },
  {
    "id": 128,
    "nombre": "Ricardo Bochini",
    "nombreCarta": "Bochini",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "MED",
    "posDetalle": "MCO",
    "pico": 1984,
    "club": "Independiente",
    "siglaClub": "IND",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 83,
      "tir": 95,
      "pas": 79,
      "reg": 99,
      "def": 67,
      "fis": 77
    },
    "ata": 94,
    "cre": 87,
    "def": 70,
    "arq": 10
  },
  {
    "id": 129,
    "nombre": "Pelé",
    "nombreCarta": "Pelé",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1970,
    "club": "Santos",
    "siglaClub": "SAN",
    "ovr": 99,
    "categoria": "Leyenda",
    "carta": {
      "rit": 99,
      "tir": 99,
      "pas": 97,
      "reg": 99,
      "def": 65,
      "fis": 99
    },
    "ata": 99,
    "cre": 98,
    "def": 74,
    "arq": 10
  },
  {
    "id": 130,
    "nombre": "Lionel Messi",
    "nombreCarta": "Messi",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2012,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 99,
    "categoria": "Leyenda",
    "carta": {
      "rit": 94,
      "tir": 99,
      "pas": 92,
      "reg": 99,
      "def": 38,
      "fis": 68
    },
    "ata": 98,
    "cre": 95,
    "def": 46,
    "arq": 10
  },
  {
    "id": 131,
    "nombre": "Johan Cruyff",
    "nombreCarta": "Cruyff",
    "pais": "Países Bajos",
    "bandera": "🇳🇱",
    "posicion": "DEL",
    "posDetalle": "SD",
    "pico": 1974,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 97,
    "categoria": "Leyenda",
    "carta": {
      "rit": 97,
      "tir": 96,
      "pas": 99,
      "reg": 99,
      "def": 59,
      "fis": 91
    },
    "ata": 97,
    "cre": 99,
    "def": 67,
    "arq": 10
  },
  {
    "id": 132,
    "nombre": "Alfredo Di Stéfano",
    "nombreCarta": "Di Stéfano",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1957,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 97,
    "categoria": "Leyenda",
    "carta": {
      "rit": 99,
      "tir": 95,
      "pas": 95,
      "reg": 99,
      "def": 63,
      "fis": 99
    },
    "ata": 97,
    "cre": 97,
    "def": 72,
    "arq": 10
  },
  {
    "id": 133,
    "nombre": "Ronaldo Nazário",
    "nombreCarta": "Ronaldo",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1997,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 97,
    "categoria": "Leyenda",
    "carta": {
      "rit": 99,
      "tir": 95,
      "pas": 91,
      "reg": 99,
      "def": 55,
      "fis": 93
    },
    "ata": 97,
    "cre": 94,
    "def": 65,
    "arq": 10
  },
  {
    "id": 134,
    "nombre": "Cristiano Ronaldo",
    "nombreCarta": "C. Ronaldo",
    "pais": "Portugal",
    "bandera": "🇵🇹",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2014,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 97,
    "categoria": "Leyenda",
    "carta": {
      "rit": 93,
      "tir": 99,
      "pas": 89,
      "reg": 93,
      "def": 61,
      "fis": 99
    },
    "ata": 96,
    "cre": 91,
    "def": 71,
    "arq": 10
  },
  {
    "id": 135,
    "nombre": "Ferenc Puskás",
    "nombreCarta": "Puskás",
    "pais": "Hungría",
    "bandera": "🇭🇺",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1953,
    "club": "Honvéd",
    "siglaClub": "HON",
    "ovr": 96,
    "categoria": "Leyenda",
    "carta": {
      "rit": 90,
      "tir": 99,
      "pas": 86,
      "reg": 88,
      "def": 56,
      "fis": 98
    },
    "ata": 94,
    "cre": 87,
    "def": 67,
    "arq": 10
  },
  {
    "id": 136,
    "nombre": "Garrincha",
    "nombreCarta": "Garrincha",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEL",
    "posDetalle": "ED",
    "pico": 1962,
    "club": "Botafogo",
    "siglaClub": "BOT",
    "ovr": 95,
    "categoria": "Leyenda",
    "carta": {
      "rit": 99,
      "tir": 91,
      "pas": 97,
      "reg": 99,
      "def": 55,
      "fis": 87
    },
    "ata": 95,
    "cre": 98,
    "def": 63,
    "arq": 10
  },
  {
    "id": 137,
    "nombre": "Eusébio",
    "nombreCarta": "Eusébio",
    "pais": "Portugal",
    "bandera": "🇵🇹",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1966,
    "club": "Benfica",
    "siglaClub": "BEN",
    "ovr": 95,
    "categoria": "Leyenda",
    "carta": {
      "rit": 99,
      "tir": 91,
      "pas": 93,
      "reg": 99,
      "def": 61,
      "fis": 97
    },
    "ata": 95,
    "cre": 95,
    "def": 70,
    "arq": 10
  },
  {
    "id": 138,
    "nombre": "Gerd Müller",
    "nombreCarta": "Müller",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1972,
    "club": "Bayern Múnich",
    "siglaClub": "BAY",
    "ovr": 95,
    "categoria": "Leyenda",
    "carta": {
      "rit": 89,
      "tir": 99,
      "pas": 85,
      "reg": 87,
      "def": 55,
      "fis": 97
    },
    "ata": 93,
    "cre": 86,
    "def": 66,
    "arq": 10
  },
  {
    "id": 139,
    "nombre": "Marco van Basten",
    "nombreCarta": "Van Basten",
    "pais": "Países Bajos",
    "bandera": "🇳🇱",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1989,
    "club": "Milan",
    "siglaClub": "MIL",
    "ovr": 95,
    "categoria": "Leyenda",
    "carta": {
      "rit": 99,
      "tir": 91,
      "pas": 93,
      "reg": 99,
      "def": 61,
      "fis": 97
    },
    "ata": 95,
    "cre": 95,
    "def": 70,
    "arq": 10
  },
  {
    "id": 140,
    "nombre": "Romário",
    "nombreCarta": "Romário",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1994,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 94,
    "categoria": "Crack",
    "carta": {
      "rit": 88,
      "tir": 99,
      "pas": 84,
      "reg": 86,
      "def": 54,
      "fis": 96
    },
    "ata": 93,
    "cre": 85,
    "def": 65,
    "arq": 10
  },
  {
    "id": 141,
    "nombre": "Roberto Baggio",
    "nombreCarta": "Baggio",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "DEL",
    "posDetalle": "SD",
    "pico": 1994,
    "club": "Juventus",
    "siglaClub": "JUV",
    "ovr": 94,
    "categoria": "Crack",
    "carta": {
      "rit": 94,
      "tir": 91,
      "pas": 99,
      "reg": 99,
      "def": 56,
      "fis": 88
    },
    "ata": 94,
    "cre": 99,
    "def": 64,
    "arq": 10
  },
  {
    "id": 142,
    "nombre": "Thierry Henry",
    "nombreCarta": "Henry",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2004,
    "club": "Arsenal",
    "siglaClub": "ARS",
    "ovr": 93,
    "categoria": "Crack",
    "carta": {
      "rit": 97,
      "tir": 89,
      "pas": 91,
      "reg": 97,
      "def": 59,
      "fis": 95
    },
    "ata": 93,
    "cre": 93,
    "def": 68,
    "arq": 10
  },
  {
    "id": 143,
    "nombre": "George Best",
    "nombreCarta": "Best",
    "pais": "Irlanda del Norte",
    "bandera": "🇬🇧",
    "posicion": "DEL",
    "posDetalle": "EI",
    "pico": 1968,
    "club": "Manchester United",
    "siglaClub": "MUN",
    "ovr": 93,
    "categoria": "Crack",
    "carta": {
      "rit": 99,
      "tir": 87,
      "pas": 95,
      "reg": 99,
      "def": 53,
      "fis": 85
    },
    "ata": 93,
    "cre": 97,
    "def": 61,
    "arq": 10
  },
  {
    "id": 144,
    "nombre": "Giuseppe Meazza",
    "nombreCarta": "Meazza",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1934,
    "club": "Inter",
    "siglaClub": "INT",
    "ovr": 93,
    "categoria": "Crack",
    "carta": {
      "rit": 97,
      "tir": 89,
      "pas": 91,
      "reg": 97,
      "def": 59,
      "fis": 95
    },
    "ata": 93,
    "cre": 93,
    "def": 68,
    "arq": 10
  },
  {
    "id": 145,
    "nombre": "Kylian Mbappé",
    "nombreCarta": "Mbappé",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "DEL",
    "posDetalle": "EI",
    "pico": 2022,
    "club": "Paris Saint-Germain",
    "siglaClub": "PSG",
    "ovr": 92,
    "categoria": "Crack",
    "carta": {
      "rit": 99,
      "tir": 85,
      "pas": 86,
      "reg": 99,
      "def": 50,
      "fis": 88
    },
    "ata": 92,
    "cre": 91,
    "def": 60,
    "arq": 10
  },
  {
    "id": 146,
    "nombre": "Neymar",
    "nombreCarta": "Neymar",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEL",
    "posDetalle": "EI",
    "pico": 2015,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 92,
    "categoria": "Crack",
    "carta": {
      "rit": 99,
      "tir": 85,
      "pas": 94,
      "reg": 99,
      "def": 52,
      "fis": 84
    },
    "ata": 92,
    "cre": 96,
    "def": 60,
    "arq": 10
  },
  {
    "id": 147,
    "nombre": "Karl-Heinz Rummenigge",
    "nombreCarta": "Rummenigge",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1980,
    "club": "Bayern Múnich",
    "siglaClub": "BAY",
    "ovr": 92,
    "categoria": "Crack",
    "carta": {
      "rit": 96,
      "tir": 88,
      "pas": 90,
      "reg": 96,
      "def": 58,
      "fis": 94
    },
    "ata": 92,
    "cre": 92,
    "def": 67,
    "arq": 10
  },
  {
    "id": 148,
    "nombre": "Rivaldo",
    "nombreCarta": "Rivaldo",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEL",
    "posDetalle": "EI",
    "pico": 1999,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 92,
    "categoria": "Crack",
    "carta": {
      "rit": 92,
      "tir": 88,
      "pas": 99,
      "reg": 99,
      "def": 54,
      "fis": 86
    },
    "ata": 92,
    "cre": 99,
    "def": 62,
    "arq": 10
  },
  {
    "id": 149,
    "nombre": "Robert Lewandowski",
    "nombreCarta": "Lewandowski",
    "pais": "Polonia",
    "bandera": "🇵🇱",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2020,
    "club": "Bayern Múnich",
    "siglaClub": "BAY",
    "ovr": 92,
    "categoria": "Crack",
    "carta": {
      "rit": 88,
      "tir": 96,
      "pas": 84,
      "reg": 88,
      "def": 56,
      "fis": 99
    },
    "ata": 92,
    "cre": 86,
    "def": 67,
    "arq": 10
  },
  {
    "id": 150,
    "nombre": "Luis Suárez",
    "nombreCarta": "Suárez",
    "pais": "Uruguay",
    "bandera": "🇺🇾",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2016,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 95,
      "tir": 87,
      "pas": 89,
      "reg": 95,
      "def": 57,
      "fis": 93
    },
    "ata": 91,
    "cre": 91,
    "def": 66,
    "arq": 10
  },
  {
    "id": 151,
    "nombre": "Karim Benzema",
    "nombreCarta": "Benzema",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2022,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 91,
      "tir": 86,
      "pas": 99,
      "reg": 99,
      "def": 53,
      "fis": 85
    },
    "ata": 91,
    "cre": 99,
    "def": 61,
    "arq": 10
  },
  {
    "id": 152,
    "nombre": "Zlatan Ibrahimović",
    "nombreCarta": "Ibrahimović",
    "pais": "Suecia",
    "bandera": "🇸🇪",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2013,
    "club": "Paris Saint-Germain",
    "siglaClub": "PSG",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 87,
      "tir": 95,
      "pas": 83,
      "reg": 87,
      "def": 55,
      "fis": 99
    },
    "ata": 91,
    "cre": 85,
    "def": 66,
    "arq": 10
  },
  {
    "id": 153,
    "nombre": "Gabriel Batistuta",
    "nombreCarta": "Batistuta",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1995,
    "club": "Fiorentina",
    "siglaClub": "FIO",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 87,
      "tir": 95,
      "pas": 83,
      "reg": 87,
      "def": 55,
      "fis": 99
    },
    "ata": 91,
    "cre": 85,
    "def": 66,
    "arq": 10
  },
  {
    "id": 154,
    "nombre": "Andriy Shevchenko",
    "nombreCarta": "Shevchenko",
    "pais": "Ucrania",
    "bandera": "🇺🇦",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2004,
    "club": "Milan",
    "siglaClub": "MIL",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 87,
      "tir": 95,
      "pas": 83,
      "reg": 87,
      "def": 55,
      "fis": 99
    },
    "ata": 91,
    "cre": 85,
    "def": 66,
    "arq": 10
  },
  {
    "id": 155,
    "nombre": "Omar Sívori",
    "nombreCarta": "Sívori",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEL",
    "posDetalle": "SD",
    "pico": 1961,
    "club": "Juventus",
    "siglaClub": "JUV",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 91,
      "tir": 86,
      "pas": 99,
      "reg": 99,
      "def": 53,
      "fis": 85
    },
    "ata": 91,
    "cre": 99,
    "def": 61,
    "arq": 10
  },
  {
    "id": 156,
    "nombre": "Francisco Gento",
    "nombreCarta": "Gento",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "DEL",
    "posDetalle": "EI",
    "pico": 1958,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 83,
      "pas": 93,
      "reg": 99,
      "def": 51,
      "fis": 83
    },
    "ata": 91,
    "cre": 95,
    "def": 59,
    "arq": 10
  },
  {
    "id": 157,
    "nombre": "László Kubala",
    "nombreCarta": "Kubala",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "DEL",
    "posDetalle": "SD",
    "pico": 1952,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 91,
      "tir": 86,
      "pas": 99,
      "reg": 99,
      "def": 53,
      "fis": 85
    },
    "ata": 91,
    "cre": 99,
    "def": 61,
    "arq": 10
  },
  {
    "id": 158,
    "nombre": "Leônidas",
    "nombreCarta": "Leônidas",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1938,
    "club": "Flamengo",
    "siglaClub": "FLA",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 85,
      "tir": 98,
      "pas": 81,
      "reg": 83,
      "def": 51,
      "fis": 93
    },
    "ata": 91,
    "cre": 82,
    "def": 62,
    "arq": 10
  },
  {
    "id": 159,
    "nombre": "Raymond Kopa",
    "nombreCarta": "Kopa",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "DEL",
    "posDetalle": "ED",
    "pico": 1958,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 91,
      "tir": 86,
      "pas": 99,
      "reg": 99,
      "def": 53,
      "fis": 85
    },
    "ata": 91,
    "cre": 99,
    "def": 61,
    "arq": 10
  },
  {
    "id": 160,
    "nombre": "Stanley Matthews",
    "nombreCarta": "Matthews",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "DEL",
    "posDetalle": "ED",
    "pico": 1953,
    "club": "Blackpool",
    "siglaClub": "BLP",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 83,
      "pas": 93,
      "reg": 99,
      "def": 51,
      "fis": 83
    },
    "ata": 91,
    "cre": 95,
    "def": 59,
    "arq": 10
  },
  {
    "id": 161,
    "nombre": "Erling Haaland",
    "nombreCarta": "Haaland",
    "pais": "Noruega",
    "bandera": "🇳🇴",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2023,
    "club": "Manchester City",
    "siglaClub": "MCI",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 87,
      "tir": 95,
      "pas": 83,
      "reg": 87,
      "def": 55,
      "fis": 99
    },
    "ata": 91,
    "cre": 85,
    "def": 66,
    "arq": 10
  },
  {
    "id": 162,
    "nombre": "Jairzinho",
    "nombreCarta": "Jairzinho",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEL",
    "posDetalle": "ED",
    "pico": 1970,
    "club": "Botafogo",
    "siglaClub": "BOT",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 83,
      "pas": 93,
      "reg": 99,
      "def": 51,
      "fis": 83
    },
    "ata": 91,
    "cre": 95,
    "def": 59,
    "arq": 10
  },
  {
    "id": 163,
    "nombre": "Sándor Kocsis",
    "nombreCarta": "Kocsis",
    "pais": "Hungría",
    "bandera": "🇭🇺",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1954,
    "club": "Honvéd",
    "siglaClub": "HON",
    "ovr": 91,
    "categoria": "Estrella",
    "carta": {
      "rit": 85,
      "tir": 98,
      "pas": 81,
      "reg": 83,
      "def": 51,
      "fis": 93
    },
    "ata": 91,
    "cre": 82,
    "def": 62,
    "arq": 10
  },
  {
    "id": 164,
    "nombre": "Dennis Bergkamp",
    "nombreCarta": "Bergkamp",
    "pais": "Países Bajos",
    "bandera": "🇳🇱",
    "posicion": "DEL",
    "posDetalle": "SD",
    "pico": 1998,
    "club": "Arsenal",
    "siglaClub": "ARS",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 90,
      "tir": 85,
      "pas": 98,
      "reg": 99,
      "def": 52,
      "fis": 84
    },
    "ata": 90,
    "cre": 98,
    "def": 60,
    "arq": 10
  },
  {
    "id": 165,
    "nombre": "Mario Kempes",
    "nombreCarta": "Kempes",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1978,
    "club": "Valencia",
    "siglaClub": "VAL",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 94,
      "tir": 86,
      "pas": 88,
      "reg": 94,
      "def": 56,
      "fis": 92
    },
    "ata": 90,
    "cre": 90,
    "def": 65,
    "arq": 10
  },
  {
    "id": 166,
    "nombre": "Hristo Stoichkov",
    "nombreCarta": "Stoichkov",
    "pais": "Bulgaria",
    "bandera": "🇧🇬",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1994,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 86,
      "tir": 94,
      "pas": 82,
      "reg": 86,
      "def": 54,
      "fis": 99
    },
    "ata": 90,
    "cre": 84,
    "def": 65,
    "arq": 10
  },
  {
    "id": 167,
    "nombre": "George Weah",
    "nombreCarta": "Weah",
    "pais": "Liberia",
    "bandera": "🇱🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1995,
    "club": "Milan",
    "siglaClub": "MIL",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 94,
      "tir": 86,
      "pas": 88,
      "reg": 94,
      "def": 56,
      "fis": 92
    },
    "ata": 90,
    "cre": 90,
    "def": 65,
    "arq": 10
  },
  {
    "id": 168,
    "nombre": "Samuel Eto'o",
    "nombreCarta": "Eto'o",
    "pais": "Camerún",
    "bandera": "🇨🇲",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2006,
    "club": "Barcelona",
    "siglaClub": "BAR",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 82,
      "pas": 84,
      "reg": 98,
      "def": 48,
      "fis": 86
    },
    "ata": 90,
    "cre": 90,
    "def": 58,
    "arq": 10
  },
  {
    "id": 169,
    "nombre": "Arjen Robben",
    "nombreCarta": "Robben",
    "pais": "Países Bajos",
    "bandera": "🇳🇱",
    "posicion": "DEL",
    "posDetalle": "ED",
    "pico": 2013,
    "club": "Bayern Múnich",
    "siglaClub": "BAY",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 81,
      "pas": 92,
      "reg": 99,
      "def": 50,
      "fis": 82
    },
    "ata": 90,
    "cre": 95,
    "def": 58,
    "arq": 10
  },
  {
    "id": 170,
    "nombre": "Mohamed Salah",
    "nombreCarta": "Salah",
    "pais": "Egipto",
    "bandera": "🇪🇬",
    "posicion": "DEL",
    "posDetalle": "ED",
    "pico": 2018,
    "club": "Liverpool",
    "siglaClub": "LIV",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 81,
      "pas": 92,
      "reg": 99,
      "def": 50,
      "fis": 82
    },
    "ata": 90,
    "cre": 95,
    "def": 58,
    "arq": 10
  },
  {
    "id": 171,
    "nombre": "Kenny Dalglish",
    "nombreCarta": "Dalglish",
    "pais": "Escocia",
    "bandera": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "posicion": "DEL",
    "posDetalle": "SD",
    "pico": 1979,
    "club": "Liverpool",
    "siglaClub": "LIV",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 90,
      "tir": 85,
      "pas": 98,
      "reg": 99,
      "def": 52,
      "fis": 84
    },
    "ata": 90,
    "cre": 98,
    "def": 60,
    "arq": 10
  },
  {
    "id": 172,
    "nombre": "Denis Law",
    "nombreCarta": "Denis Law",
    "pais": "Escocia",
    "bandera": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1964,
    "club": "Manchester United",
    "siglaClub": "MUN",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 84,
      "tir": 97,
      "pas": 80,
      "reg": 82,
      "def": 50,
      "fis": 92
    },
    "ata": 90,
    "cre": 81,
    "def": 61,
    "arq": 10
  },
  {
    "id": 173,
    "nombre": "Just Fontaine",
    "nombreCarta": "Fontaine",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1958,
    "club": "Stade de Reims",
    "siglaClub": "REI",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 84,
      "tir": 97,
      "pas": 80,
      "reg": 82,
      "def": 50,
      "fis": 92
    },
    "ata": 90,
    "cre": 81,
    "def": 61,
    "arq": 10
  },
  {
    "id": 174,
    "nombre": "Paolo Rossi",
    "nombreCarta": "Rossi",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1982,
    "club": "Juventus",
    "siglaClub": "JUV",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 84,
      "tir": 97,
      "pas": 80,
      "reg": 82,
      "def": 50,
      "fis": 92
    },
    "ata": 90,
    "cre": 81,
    "def": 61,
    "arq": 10
  },
  {
    "id": 175,
    "nombre": "Luigi Riva",
    "nombreCarta": "Riva",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1970,
    "club": "Cagliari",
    "siglaClub": "CAG",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 86,
      "tir": 94,
      "pas": 82,
      "reg": 86,
      "def": 54,
      "fis": 99
    },
    "ata": 90,
    "cre": 84,
    "def": 65,
    "arq": 10
  },
  {
    "id": 176,
    "nombre": "Tostão",
    "nombreCarta": "Tostão",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1970,
    "club": "Cruzeiro",
    "siglaClub": "CRU",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 90,
      "tir": 85,
      "pas": 98,
      "reg": 99,
      "def": 52,
      "fis": 84
    },
    "ata": 90,
    "cre": 98,
    "def": 60,
    "arq": 10
  },
  {
    "id": 177,
    "nombre": "Raúl González",
    "nombreCarta": "Raúl",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2001,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 94,
      "tir": 86,
      "pas": 88,
      "reg": 94,
      "def": 56,
      "fis": 92
    },
    "ata": 90,
    "cre": 90,
    "def": 65,
    "arq": 10
  },
  {
    "id": 178,
    "nombre": "Francesco Totti",
    "nombreCarta": "Totti",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "DEL",
    "posDetalle": "SD",
    "pico": 2007,
    "club": "Roma",
    "siglaClub": "ROM",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 90,
      "tir": 85,
      "pas": 98,
      "reg": 99,
      "def": 52,
      "fis": 84
    },
    "ata": 90,
    "cre": 98,
    "def": 60,
    "arq": 10
  },
  {
    "id": 179,
    "nombre": "Alessandro Del Piero",
    "nombreCarta": "Del Piero",
    "pais": "Italia",
    "bandera": "🇮🇹",
    "posicion": "DEL",
    "posDetalle": "SD",
    "pico": 1998,
    "club": "Juventus",
    "siglaClub": "JUV",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 90,
      "tir": 85,
      "pas": 98,
      "reg": 99,
      "def": 52,
      "fis": 84
    },
    "ata": 90,
    "cre": 98,
    "def": 60,
    "arq": 10
  },
  {
    "id": 180,
    "nombre": "Vinícius Júnior",
    "nombreCarta": "Vinícius Jr",
    "pais": "Brasil",
    "bandera": "🇧🇷",
    "posicion": "DEL",
    "posDetalle": "EI",
    "pico": 2024,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 81,
      "pas": 92,
      "reg": 99,
      "def": 50,
      "fis": 82
    },
    "ata": 90,
    "cre": 95,
    "def": 58,
    "arq": 10
  },
  {
    "id": 181,
    "nombre": "José Manuel Moreno",
    "nombreCarta": "Moreno",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEL",
    "posDetalle": "SD",
    "pico": 1942,
    "club": "River Plate",
    "siglaClub": "RIV",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 94,
      "tir": 86,
      "pas": 88,
      "reg": 94,
      "def": 56,
      "fis": 92
    },
    "ata": 90,
    "cre": 90,
    "def": 65,
    "arq": 10
  },
  {
    "id": 182,
    "nombre": "Kevin Keegan",
    "nombreCarta": "Keegan",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1979,
    "club": "Hamburgo",
    "siglaClub": "HAM",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 94,
      "tir": 86,
      "pas": 88,
      "reg": 94,
      "def": 56,
      "fis": 92
    },
    "ata": 90,
    "cre": 90,
    "def": 65,
    "arq": 10
  },
  {
    "id": 183,
    "nombre": "Gunnar Nordahl",
    "nombreCarta": "Nordahl",
    "pais": "Suecia",
    "bandera": "🇸🇪",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1950,
    "club": "Milan",
    "siglaClub": "MIL",
    "ovr": 90,
    "categoria": "Estrella",
    "carta": {
      "rit": 86,
      "tir": 94,
      "pas": 82,
      "reg": 86,
      "def": 54,
      "fis": 99
    },
    "ata": 90,
    "cre": 84,
    "def": 65,
    "arq": 10
  },
  {
    "id": 184,
    "nombre": "Oleg Blokhin",
    "nombreCarta": "Blokhin",
    "pais": "Ucrania",
    "bandera": "🇺🇦",
    "posicion": "DEL",
    "posDetalle": "EI",
    "pico": 1975,
    "club": "Dinamo Kiev",
    "siglaClub": "DKI",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 79,
      "pas": 91,
      "reg": 99,
      "def": 49,
      "fis": 81
    },
    "ata": 89,
    "cre": 94,
    "def": 57,
    "arq": 10
  },
  {
    "id": 185,
    "nombre": "Eden Hazard",
    "nombreCarta": "Hazard",
    "pais": "Bélgica",
    "bandera": "🇧🇪",
    "posicion": "DEL",
    "posDetalle": "EI",
    "pico": 2015,
    "club": "Chelsea",
    "siglaClub": "CHE",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 99,
      "tir": 79,
      "pas": 91,
      "reg": 99,
      "def": 49,
      "fis": 81
    },
    "ata": 89,
    "cre": 94,
    "def": 57,
    "arq": 10
  },
  {
    "id": 186,
    "nombre": "Harry Kane",
    "nombreCarta": "Kane",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2024,
    "club": "Bayern Múnich",
    "siglaClub": "BAY",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 93,
      "tir": 85,
      "pas": 87,
      "reg": 93,
      "def": 55,
      "fis": 91
    },
    "ata": 89,
    "cre": 89,
    "def": 64,
    "arq": 10
  },
  {
    "id": 187,
    "nombre": "Didier Drogba",
    "nombreCarta": "Drogba",
    "pais": "Costa de Marfil",
    "bandera": "🇨🇮",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2010,
    "club": "Chelsea",
    "siglaClub": "CHE",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 85,
      "tir": 93,
      "pas": 81,
      "reg": 85,
      "def": 53,
      "fis": 99
    },
    "ata": 89,
    "cre": 83,
    "def": 65,
    "arq": 10
  },
  {
    "id": 188,
    "nombre": "Alan Shearer",
    "nombreCarta": "Shearer",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1996,
    "club": "Blackburn Rovers",
    "siglaClub": "BLB",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 85,
      "tir": 93,
      "pas": 81,
      "reg": 85,
      "def": 53,
      "fis": 99
    },
    "ata": 89,
    "cre": 83,
    "def": 65,
    "arq": 10
  },
  {
    "id": 189,
    "nombre": "Wayne Rooney",
    "nombreCarta": "Rooney",
    "pais": "Inglaterra",
    "bandera": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "posicion": "DEL",
    "posDetalle": "SD",
    "pico": 2010,
    "club": "Manchester United",
    "siglaClub": "MUN",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 93,
      "tir": 85,
      "pas": 87,
      "reg": 93,
      "def": 55,
      "fis": 91
    },
    "ata": 89,
    "cre": 89,
    "def": 64,
    "arq": 10
  },
  {
    "id": 190,
    "nombre": "Hugo Sánchez",
    "nombreCarta": "Hugo Sánchez",
    "pais": "México",
    "bandera": "🇲🇽",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1990,
    "club": "Real Madrid",
    "siglaClub": "RMA",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 83,
      "tir": 96,
      "pas": 79,
      "reg": 81,
      "def": 49,
      "fis": 91
    },
    "ata": 89,
    "cre": 80,
    "def": 60,
    "arq": 10
  },
  {
    "id": 191,
    "nombre": "Antoine Griezmann",
    "nombreCarta": "Griezmann",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "DEL",
    "posDetalle": "SD",
    "pico": 2018,
    "club": "Atlético de Madrid",
    "siglaClub": "ATM",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 89,
      "tir": 83,
      "pas": 97,
      "reg": 99,
      "def": 51,
      "fis": 83
    },
    "ata": 89,
    "cre": 98,
    "def": 59,
    "arq": 10
  },
  {
    "id": 192,
    "nombre": "Eric Cantona",
    "nombreCarta": "Cantona",
    "pais": "Francia",
    "bandera": "🇫🇷",
    "posicion": "DEL",
    "posDetalle": "SD",
    "pico": 1996,
    "club": "Manchester United",
    "siglaClub": "MUN",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 89,
      "tir": 83,
      "pas": 97,
      "reg": 99,
      "def": 51,
      "fis": 83
    },
    "ata": 89,
    "cre": 98,
    "def": 59,
    "arq": 10
  },
  {
    "id": 193,
    "nombre": "Jürgen Klinsmann",
    "nombreCarta": "Klinsmann",
    "pais": "Alemania",
    "bandera": "🇩🇪",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1990,
    "club": "Inter",
    "siglaClub": "INT",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 83,
      "tir": 96,
      "pas": 79,
      "reg": 81,
      "def": 49,
      "fis": 91
    },
    "ata": 89,
    "cre": 80,
    "def": 60,
    "arq": 10
  },
  {
    "id": 194,
    "nombre": "Sergio Agüero",
    "nombreCarta": "Agüero",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2014,
    "club": "Manchester City",
    "siglaClub": "MCI",
    "ovr": 89,
    "categoria": "Estrella",
    "carta": {
      "rit": 83,
      "tir": 96,
      "pas": 79,
      "reg": 81,
      "def": 49,
      "fis": 91
    },
    "ata": 89,
    "cre": 80,
    "def": 60,
    "arq": 10
  },
  {
    "id": 195,
    "nombre": "Hernán Crespo",
    "nombreCarta": "Crespo",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2001,
    "club": "Lazio",
    "siglaClub": "LAZ",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 82,
      "tir": 95,
      "pas": 78,
      "reg": 80,
      "def": 48,
      "fis": 90
    },
    "ata": 88,
    "cre": 79,
    "def": 59,
    "arq": 10
  },
  {
    "id": 196,
    "nombre": "Diego Forlán",
    "nombreCarta": "Forlán",
    "pais": "Uruguay",
    "bandera": "🇺🇾",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2010,
    "club": "Atlético de Madrid",
    "siglaClub": "ATM",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 92,
      "tir": 84,
      "pas": 86,
      "reg": 92,
      "def": 54,
      "fis": 90
    },
    "ata": 88,
    "cre": 88,
    "def": 63,
    "arq": 10
  },
  {
    "id": 197,
    "nombre": "Fernando Torres",
    "nombreCarta": "F. Torres",
    "pais": "España",
    "bandera": "🇪🇸",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 2008,
    "club": "Liverpool",
    "siglaClub": "LIV",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 99,
      "tir": 79,
      "pas": 82,
      "reg": 96,
      "def": 46,
      "fis": 84
    },
    "ata": 88,
    "cre": 88,
    "def": 56,
    "arq": 10
  },
  {
    "id": 198,
    "nombre": "Alberto Spencer",
    "nombreCarta": "Spencer",
    "pais": "Ecuador",
    "bandera": "🇪🇨",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1961,
    "club": "Peñarol",
    "siglaClub": "PEN",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 82,
      "tir": 95,
      "pas": 78,
      "reg": 80,
      "def": 48,
      "fis": 90
    },
    "ata": 88,
    "cre": 79,
    "def": 59,
    "arq": 10
  },
  {
    "id": 199,
    "nombre": "Ángel Labruna",
    "nombreCarta": "Labruna",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1945,
    "club": "River Plate",
    "siglaClub": "RIV",
    "ovr": 88,
    "categoria": "Figura",
    "carta": {
      "rit": 88,
      "tir": 81,
      "pas": 96,
      "reg": 99,
      "def": 50,
      "fis": 82
    },
    "ata": 88,
    "cre": 97,
    "def": 58,
    "arq": 10
  },
  {
    "id": 200,
    "nombre": "Claudio Caniggia",
    "nombreCarta": "Caniggia",
    "pais": "Argentina",
    "bandera": "🇦🇷",
    "posicion": "DEL",
    "posDetalle": "DC",
    "pico": 1990,
    "club": "Atalanta",
    "siglaClub": "ATA",
    "ovr": 87,
    "categoria": "Figura",
    "carta": {
      "rit": 97,
      "tir": 84,
      "pas": 72,
      "reg": 88,
      "def": 35,
      "fis": 70
    },
    "ata": 88,
    "cre": 78,
    "def": 44,
    "arq": 10
  }
];

  return JUGADORES;
});
